version: 0.2
phases: 
  install:
    runtime-versions:
        docker: 18 
  pre_build: 
    commands: 
    - echo Logging in to Amazon ECR.... 
    - aws --version
    # update the following line with your own region
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - REPOSITORY_URI=344195135476.dkr.ecr.us-east-1.amazonaws.com/dockerimages 
  build: 
    commands: 
    - echo Build started on `date` 
    - echo pulling the Docker image... 
    - pulled_image=$(docker pull 344195135476.dkr.ecr.us-east-1.amazonaws.com/dockerimages:8a2fe67)
    - echo $pulled_image
    - docker build -t pull-push .
    - docker tag pull-push:latest 344195135476.dkr.ecr.us-east-1.amazonaws.com/pull-push:latest
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pulled and pushed to repo
    # update the following line with the URI of your own ECR repository
    - docker push 344195135476.dkr.ecr.us-east-1.amazonaws.com/pull-push:latest
    - echo Writing image definitions file... 
    #- printf '[{"ImageURI":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
    - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
